# Autogenerated config.py
config.load_autoconfig(False)

c.auto_save.session = True

c.content.media.audio_capture = True

# Display PDFS in browser

c.content.pdfjs = True

### Autohide cookies banners
c.content.blocking.adblock.lists = ['https://easylist.to/easylist/easylist.txt', 'https://easylist.to/easylist/easyprivacy.txt', 'https://easylist-downloads.adblockplus.org/easylistdutch.txt', 'https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt', 'https://www.i-dont-care-about-cookies.eu/abp/', 'https://secure.fanboy.co.nz/fanboy-cookiemonster.txt']

# Default Config
c.url.default_page = 'https://search.brave.com/'
c.url.searchengines = {'DEFAULT': 'https://search.brave.com/search?source=web&q={}'}
c.url.start_pages = 'https://search.brave.com/'

c.downloads.location.prompt = True
c.downloads.location.suggestion = 'both'  # path, filename, b


c.downloads.location.directory = '~/Descargas'
c.tabs.background = True

# Bindings for normal mode
config.bind('M', 'hint links spawn mpv {hint-url}')
config.bind(',m', 'spawn mpv {url}')
config.bind(',p', 'spawn --userscript rofi-bitwarden-fill')
config.bind('P', 'spawn --userscript bw-dmenu-fill')
config.bind('xb', 'config-cycle statusbar.show always never')
config.bind('xt', 'config-cycle tabs.show always never')
config.bind('xx', 'config-cycle statusbar.show always never;; config-cycle tabs.show always never')


# Fonts
c.fonts.default_family = '"SauceCodePro Nerd Font"'

c.fonts.default_size = '11pt'

c.fonts.completion.entry = '11pt "SauceCodePro Nerd Font"'
c.fonts.statusbar = '11pt "SauceCodePro Nerd Font"'
c.fonts.prompts = 'default_size sans-serif'

# Colors

c.colors.tabs.bar.bg = '#1c1f34'
c.colors.tabs.odd.bg = '#282c34'
c.colors.tabs.even.bg = '#282c34'
c.colors.tabs.selected.odd.bg = '#282c34'
c.colors.tabs.selected.even.bg = '#282c34'
c.colors.tabs.pinned.odd.bg = 'seagreen'
c.colors.tabs.pinned.even.bg = 'darkseagreen'
c.colors.tabs.pinned.selected.odd.bg = '#282c34'

c.confirm_quit = ['multiple-tabs']
c.content.headers.user_agent = 'Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0'
c.content.canvas_reading = False

c.content.webgl = False

c.content.javascript.enabled = True

c.content.pdfjs = False

